### ISSUE TITLE
authorship, license

### ISSUE THREAD

**Issue by emeryberger** [HewlettPackard/nvthreads#2]
While I am delighted to see others building on our work, you really should acknowledge that Tongping Liu and I are the authors of _significant_ portions of the code in this repo in the AUTHORS / README files; an ack of the Dthreads and Heap Layers papers would also be appreciated. In addition, that code (Heap Layers and Dthreads) was GPL v2.0 licensed; you can't re-license it with GPL v3.0 without consent, which you haven't requested and which has not been granted. Thanks.

**Comment by terry-hsu** [comment]
Thank you for open sourcing the Dthreads library. The repository has been updated to include the Dthreads webpage and author names. We are currently working on the license issue.

**Comment by terry-hsu** [comment]
We have reverted the license from GPL v3.0 to GPL v2.0.
Thanks again for letting us know about the license issue.
